{
    "parse_time": "2025-10-10 11:04:07",
    "path": "https://www.cnvd.org.cn/flaw/show/CNVD-2025-23284",
    "spider_time": 1760094247529,
    "name": "PyTorch存在未明漏洞（CNVD-2025-23284）",
    "cnvd": "CNVD-2025-23284",
    "publish": "2025-10-10",
    "severity": "中",
    "cvss_vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
    "product": "[\"Pytorch Pytorch <2.7.0\"]",
    "cve": "CVE-2025-46149",
    "description": "PyTorch是PyTorch开源的一个Python包。PyTorch存在安全漏洞，该漏洞源于使用inductor时nn.Fold存在断言错误，目前没有详细的漏洞细节提供。",
    "flaw_type": "通用型漏洞",
    "reference": "https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a",
    "solution": "厂商已发布了漏洞修复程序，请及时关注更新：\nhttps://pytorch.org/get-started/previous-versions/?ajs_aid=277996d0-7b09-4ed6-9cea-e4ec582778fb",
    "patch": "PyTorch存在未明漏洞（CNVD-2025-23284）的补丁",
    "verify": "(暂无验证信息)",
    "submit_time": "2025-09-28",
    "open_time": "2025-10-10",
    "update_time": "2025-10-10",
    "data_summary": "769ac4eb62e84df4d9289f9abc2f4a9d"
}