{
    "parse_time": "2025-10-11 09:04:43",
    "path": "https://www.cnvd.org.cn/flaw/show/CNVD-2025-23353",
    "spider_time": 1760173483648,
    "name": "PyTorch拒绝服务漏洞（CNVD-2025-23353）",
    "cnvd": "CNVD-2025-23353",
    "publish": "2025-10-11",
    "severity": "中",
    "cvss_vector": "AV:L/AC:L/Au:S/C:N/I:N/A:C",
    "product": "[\"Pytorch Pytorch 2.6.0\"]",
    "cve": "CVE-2025-3730",
    "description": "PyTorch是PyTorch开源的一个Python包。PyTorch存在拒绝服务漏洞，该漏洞是由于torch.nn.functional.ctc_loss中的浮点异常引起的。攻击者可利用该漏洞导致拒绝服务。",
    "flaw_type": "通用型漏洞",
    "reference": "https://github.com/pytorch/pytorch/issues/150835",
    "solution": "厂商已发布了漏洞修复程序，请及时关注更新：\nhttps://pytorch.org/",
    "patch": "PyTorch拒绝服务漏洞（CNVD-2025-23353）的补丁",
    "verify": "(暂无验证信息)",
    "submit_time": "2025-04-25",
    "open_time": "2025-10-11",
    "update_time": "2025-10-11",
    "data_summary": "3b69fd6d4888450c9e9851909e0c9acc"
}